### ISSUE TITLE
transcribe fails with error: `Argument #4: Padding size should be less than the corresponding input dimension, but got: padding (200, 200) at dimension 2 of input [1, 1, 144]`

### ISSUE THREAD

**Issue by eschmidbauer** [linto-ai/whisper-timestamped#17]
Im getting an error running transcribe with these parameters:
```
model = whisper_timestamped.load_model(name="large-v2", device="cuda")
input = whisper_timestamped.load_audio(wav_file)
result = whisper_timestamped.transcribe(model, input, language="English", verbose=False, best_of=5, beam_size=5, temperature=(0.0, 0.2, 0.4, 0.6, 0.8, 1.0))
```
If i remove the `best_of=5, beam_size=5, temperature=(0.0, 0.2, 0.4, 0.6, 0.8, 1.0)`, transcribe works but the accuracy is very poor

```Traceback (most recent call last):
result = whisper_timestamped.transcribe(
  File "/root/miniconda3/envs/whisper-timestamped/lib/python3.10/site-packages/whisper_timestamped/transcribe.py", line 207, in transcribe_timestamped
    (transcription, words) = _transcribe_timestamped_naive(model, audio, **alignment_options, **whisper_options, **other_options)
  File "/root/miniconda3/envs/whisper-timestamped/lib/python3.10/site-packages/whisper_timestamped/transcribe.py", line 691, in _transcribe_timestamped_naive
    mfcc = whisper.log_mel_spectrogram(sub_audio).to(model.device)
  File "/root/miniconda3/envs/whisper-timestamped/lib/python3.10/site-packages/whisper/audio.py", line 115, in log_mel_spectrogram
    stft = torch.stft(audio, N_FFT, HOP_LENGTH, window=window, return_complex=True)
  File "/root/miniconda3/envs/whisper-timestamped/lib/python3.10/site-packages/torch/functional.py", line 630, in stft
    input = F.pad(input.view(extended_shape), [pad, pad], pad_mode)
RuntimeError: Argument #4: Padding size should be less than the corresponding input dimension, but got: padding (200, 200) at dimension 2 of input [1, 1, 144]```

**Comment by Jeronymous** [comment]
Thanks a lot for reporting @eschmidbauer 
This should be fixed now.

FYI, this failure happened when Whisper predicted too short segments.
Which is usually a bad sign. I have the feeling that it happens when the Language Model is stuck, and generates words that do not appear in the audio.
When it happens, you might see some warnings:
```
WARNING:whisper_timestamped:Got too short segment <...>. Words won't be located for this segment.
```
Meaning that you will have some text for a "segment" but not the corresponding words (because it was impossible to align words on a segment that had null or negative duration).
Then if you suspect that the problems do not come from Whisper, but from the alignment, you can open a new issue (if possible with the audio enclosed).

**Comment by eschmidbauer** [comment]
@Jeronymous thanks for the update, but it's still happening. I pulled latest `whisper-timestamped` with:
```pip install --upgrade --no-deps --force-reinstall git+https://github.com/Jeronymous/whisper-timestamped```
and re-ran the transcribe. 
Any ideas on how i can debug this further?

**Comment by Jeronymous** [comment]
Oh dear...
Can you please first double check the installed version
```
import whisper_timestamped
whisper_timestamped.__version__
```

**Comment by eschmidbauer** [comment]
![Screen Shot 2023-01-24 at 12 15 51 PM](https://user-images.githubusercontent.com/7139998/214362084-5108c573-5fef-4fc0-a208-55e740e0c51f.png)

**Comment by Jeronymous** [comment]
Thanks.
Wow... I tried something to fix.

If it still fails with `Argument #4: Padding size should be less than the corresponding input dimension, but got: padding (200, 200) at dimension 2 of input [1, 1, 200]` then what you can do to debug is go at the last line before it fails in `transcribe.py`, and print the shape of the audio : it should be very small. Try to understand why...

Note that `whisper` itself does not work on super short audio (<=0.0125 sec):
```
import whisper, torch
whisper.load_model("tiny").transcribe(torch.randn(200))

RuntimeError                              Traceback (most recent call last)
Input In [11], in <cell line: 1>()
----> 1 whisper.load_model("tiny").transcribe(torch.randn(200))

File ~/.local/lib/python3.10/site-packages/whisper/transcribe.py:89, in transcribe(model, audio, verbose, temperature, compression_ratio_threshold, logprob_threshold, no_speech_threshold, condition_on_previous_text, **decode_options)
     86 if dtype == torch.float32:
     87     decode_options["fp16"] = False
---> 89 mel = log_mel_spectrogram(audio)
     91 if decode_options.get("language", None) is None:
     92     if not model.is_multilingual:

File ~/.local/lib/python3.10/site-packages/whisper/audio.py:115, in log_mel_spectrogram(audio, n_mels)
    112     audio = torch.from_numpy(audio)
    114 window = torch.hann_window(N_FFT).to(audio.device)
--> 115 stft = torch.stft(audio, N_FFT, HOP_LENGTH, window=window, return_complex=True)
    116 magnitudes = stft[..., :-1].abs() ** 2
    118 filters = mel_filters(audio.device, n_mels)

File ~/.local/lib/python3.10/site-packages/torch/functional.py:630, in stft(input, n_fft, hop_length, win_length, window, center, pad_mode, normalized, onesided, return_complex)
    628     extended_shape = [1] * (3 - signal_dim) + list(input.size())
    629     pad = int(n_fft // 2)
--> 630     input = F.pad(input.view(extended_shape), [pad, pad], pad_mode)
    631     input = input.view(input.shape[-signal_dim:])
    632 return _VF.stft(input, n_fft, hop_length, win_length, window,  # type: ignore[attr-defined]
    633                 normalized, onesided, return_complex)

RuntimeError: Argument #4: Padding size should be less than the corresponding input dimension, but got: padding (200, 200) at dimension 2 of input [1, 1, 200]
```
But I think we are not talking about this error here.

**Comment by eschmidbauer** [comment]
thanks! appears to be fixed
